### ISSUE TITLE
Add the cosmology parameters to the values that can be explored

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/velociraptor-python#19]
It would be nice to be able to access some of the cosmological parameters like Omega_m and friends in the catalogues such that they can later be used in the pipelines.

**Comment by JBorrow** [comment]
Required for [this pull request](https://github.com/SWIFTSIM/pipeline-configs/pull/4).

**Comment by MatthieuSchaller** [comment]
Implemented in #20.
