### ISSUE TITLE
outputs for parameter search

### ISSUE THREAD

**Issue by rgbower** [SWIFTSIM/velociraptor-python#2]
Need to create the following output files from each run ... used in the parameter space search

1).  Stellar Mass Function.  Phi(M*) ... for different dentitions of mass. Include the number of objects (used for poisson uncertainty). 
format: 
M*   Phi(30pkpc) Number(30pkpc)  Phi(100pkpc)  Number(100pkpc)  Phi(total) Number(total)

example: 
#SNII_MinEnergyFraction 		0.43704
#SNII_MaxEnergyFraction 		2.0097
#SNII_rhogas_power 		0.34364
#SNII_rhogas_physdensnormfac 	9.3105
#SNII_Width_logTvir_dex 		0.42144
#BlackHoleViscousAlpha 		104370000
#BH_ConstantHeatTemp 		210320000
#BlackHoleFeedbackFactor 	0.42895
7.1 0.21408000000000074 669 0.21408000000000074 669 0.21408000000000074 669

2). radius as a function of mass.  Uses different definitions of total size and reports median.

Zzzzz -- not quite clear exactly which apertures ----  ZZZZ

example:
#SNII_MinEnergyFraction 		0.43704
#SNII_MaxEnergyFraction 		2.0097
#SNII_rhogas_power 		0.34364
#SNII_rhogas_physdensnormfac 	9.3105
#SNII_Width_logTvir_dex 		0.42144
#BlackHoleViscousAlpha 		104370000
#BH_ConstantHeatTemp 		210320000
#BlackHoleFeedbackFactor 	0.42895
7.1 0.40013418764359354 0.37636915255054226 0.7622615521329483 0.7607964220849218 666

**Comment by rgbower** [comment]
For the radii, the format needs to be ... (this includes percentiles, set them to zero for now?). We only use    med_R50_100pkpc

"Mass","med_R50_TBM","mean_R50_TBM","med_R90_TBM","mean_R90_TBM","Count","R50_20p_TBM","R50_80p_TBM","R90_20p_TBM","R90_80p_TBM",
"med_R50_100pkpc","mean_R50_100pkpc","R50_20p_100pkpc","R50_80p_100pkpc"

example:
#SNII_MinEnergyFraction 		0.40284 
#SNII_MaxEnergyFraction 		4.0635
#SNII_rhogas_power 		0.52043
#SNII_rhogas_physdensnormfac 	43.065
#SNII_Width_logTvir_dex 		0.7048
#BlackHoleViscousAlpha 		139430000
#BH_ConstantHeatTemp 		102090000
#BlackHoleFeedbackFactor 	0.089083
7.1 0.42160986022846725 0.39755152232363355 0.7849793713615838 0.7934646400467255 470 0.2500668312100716 0.5669367210054532 0.6488227054334998 0.9453246733884157 0.42160986022846725 0.39755152232363355 0.2500668312100716 0.5669367210054532 0.42160986022846725 0.3964825384014202 0.0

**Comment by rgbower** [comment]
the output masses need to be 7.1 to 11.9 in steps of 0.2 ...  I think that's it!

**Comment by JBorrow** [comment]
Hi Richard,

It's a little unclear exactly what you mean here.

1. Output mass bins - do you mean that they should be [7.1,7.3], [7.3,7.5] ... [11.7, 11.9] or should it be [7.0, 7.2] ... [11.8, 12.0]?
2. "Mass","med_R50_TBM","mean_R50_TBM","med_R90_TBM","mean_R90_TBM","Count","R50_20p_TBM","R50_80p_TBM","R90_20p_TBM","R90_80p_TBM",
"med_R50_100pkpc","mean_R50_100pkpc","R50_20p_100pkpc","R50_80p_100pkpc" - what do these mean? I am guessing "Mass 200 crit", "median/mean of R50 in that bin", "median/mean of R90 in that bin", "Number of objects in this bin", "R50, 20th percentile in that bin", "R50, 80th percentile in that bin", "median/mean R50 in 100 physical kpc". Do these mean stellar masses? Halo masses? Does TBM stand for total baryonic mass?
3. M* Phi(30pkpc) Number(30pkpc) Phi(100pkpc) Number(100pkpc) Phi(total) Number(total) - does this mean Stellar Mass, then GSFM in 30, N(M_*) for 30kpc, then the same for 100 - what does total mean? In the FoF group? Or within M200 crit?

**Comment by JBorrow** [comment]
Hi Richard,

Are the things that I have provided with the `-m` option on `velociraptor-plot` good enough for this?

**Comment by rgbower** [comment]
it all appears to be working... but let's check at tomorrow's Telecon

**Comment by JBorrow** [comment]
Let's keep this open until I have everything that Ian needs. Currently I don't output the actual histogram.
