### ISSUE TITLE
making "all the plots": key plots for comparison to observations

### ISSUE THREAD

**Issue by rgbower** [SWIFTSIM/velociraptor-python#3]
This is the list of possible plots (from my board).  I will circulate to Rob to see what's missing. First step is to make the plot from the simulation. Second step is to add observational data.

- [x] Stellar mass function [done] (all galaxies)
- [x] stellar mass - halo mass. [done] (distinguish centrals and satellites, dsc)
- [x] stellar radius vs stellar mass [done] (dsc)
- [x] black hole mass vs stellar mass (dsc)
- [x] specific star formation rate vs stellar mass (needs care handling zero sfr galaxies) (dsc)
- [x] gas mass (all, cool, star forming) vs stellar mass. (within aperture 30 or 100 kpc) (dsc)
- [x] stellar metallicity vs stellar mass (within aperture 30) (dsc)
- [x] gas metallicity vs stellar mass (within aperture 30, all, cool or sf gas) (dsc)
- [x] stellar abundance ratio (Mg/Fe) vs stellar mass (dsc)
- [x] mean stellar age vs stellar mass (dsc)
- [x] R50 gas (all, cool, sf) vs stellar mass within 100 kpc aperture. (dsc)

### Additional global plots

- [x] density - temperature diagram. (2d histogram)
- [x] stellar birth density and metal abundance  (2d histogram)
- [x] star formation history (total, of velocity raptor galaxies > 10^9 Msol) vs redshift

**Comment by JBorrow** [comment]
Extra from Rob:

* Global stellar mass density vs. time or redshift
* Star formation rate function (NB: Eagle was always poor for this)
* SMF split by active and passive (we have Schechter fits from Ivan Baldry)
* HI mass function (I argued for this at pre-Virgo, again Eagle always
struggled with this)
* Passive fractions
* Global SNIa rate
* Hot gas relations for groups (f_gas vs kT probably the most important)

We can of course also consider new plots that were missing also:

* Colour-magnitude

Plus:

I always found it instructive to include a cpu timing plot on each
webpage, we referred back to these over and over when
developing/calibrating.
