### ISSUE TITLE
Problem pipelining multiple snapshots in parallel

### ISSUE THREAD

**Issue by ymbahe** [SWIFTSIM/velociraptor-python#42]
Could this be the problem of crashes when trying to process multiple snapshots in parallel? As far as I can see, this would attempt to open the observational data set with write access:

https://github.com/SWIFTSIM/velociraptor-python/blob/bf84995fd6ff532ae26e268fc9dabbbe9ec66f97/velociraptor/observations/objects.py#L938

**Comment by JBorrow** [comment]
That'll do it!

**Comment by JBorrow** [comment]
Fixed in master and in release 0.12.3.
