### ISSUE TITLE
Angular momentum unit is wrong

### ISSUE THREAD

**Issue by bwvdnbro** [SWIFTSIM/velociraptor-python#78]
For some reason, the unit for angular momentum that is set in the registration function is wrong. It is set to length * velocity (specific angular momentum), while it really should be mass * length * velocity. I checked the VR code and the attributes of the datasets in the VR output and they all have units of proper angular momentum and not specific angular momentum.

@JBorrow, @MatthieuSchaller Any idea why the unit was set to length * velocity? Is this a genuine mistake or was there a reason behind this? Zorry gets the wrong Lstar-Mstar relation if she assumes specific angular momentum, while it works if she assumes proper angular momentum.

**Comment by JBorrow** [comment]
Likely just an error on my part. The documentation was unclear: https://velociraptor-stf.readthedocs.io/en/latest/output.html

**Comment by JBorrow** [comment]
Closed by #79
